services:
  db_showcase:
    image: postgres:14-alpine
    container_name: db_showcase
    restart: always
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "5434:5432"
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5

  app_showcase:
    build: .
    container_name: app_showcase
    restart: always
    environment:
      - API_PORT=${API_PORT}
      - DB_HOST=db_showcase
      - DB_PORT=5432
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
    ports:
      - "${API_PORT}:${API_PORT}"
    depends_on:
      db_showcase:
        condition: service_healthy

networks:
  default:
    name: tech-challenge-net
    external: true